### PR TITLE
Add RPI3 platform target

### PR DESCRIPTION
**Pull request by ronaegis**
Add Raspberry Pi 3 specific build options to the Makefile

### CODE REVIEW

**Comment by Chips-fr** [comment]
Have you seen real improvements using specific cpu flag for rpi3 ?
From the tests a made some time ago this wasn't giving any benefit...

**Comment by ronaegis** [comment]
I haven't done any synthetic benchmarks, but these are the "recommended" compile flags for the rpi3. There is a discussion thread here:
https://www.raspberrypi.org/forums/viewtopic.php?p=952086&sid=9ac75308d0f6bfc0dc87cf816fdc2600#p952086

It might not give any benefits yet, but maybe in future GCC versions, the specific ARM code generation might be improved, and it wouldn't hurt to build for the right CPU platform.

Also ideally, the Makefile should autodetect the platform (by parsing /proc/cpuinfo).

**Comment by madmonkey1907** [comment]
parsing /proc/cpuinfo is a bad idea for cross-compilation

**Comment by Chips-fr** [comment]
No real gain

**Pull request closed without merging**
