### PR TITLE
Makefile updated

### PR DESCRIPTION
**Pull request by midwan**
Added support for Raspberry Pi 3 CPU, default build platform set to rpi3

### CODE REVIEW

**Comment by Chips-fr** [comment]
Did you have some improvement using cortex-a53 ? Sysinfo give me lower number than using plain cortex-a5 on rpi3...

**Comment by joolswills** [comment]
Just FYI, I have done a variety of benchmarks for retropie, and have found no performance increase (eg benchmarking with quake). On RetroPie rpi3 shares all rpi2 binaries because of this, although building from source on rpi we do use cortex-a53 (even though it makes no difference as mentioned).

**Comment by Chips-fr** [comment]
Thanks for sharing. uae4arm could even be slightly worst :)

**Comment by joolswills** [comment]
I misread btw - I was comparing against cortex-a7 not a5 - did you mean a7 or ?

**Comment by Chips-fr** [comment]
no it was a mistake. I compare A7 vs A53 on Rpi3...

**Comment by midwan** [comment]
I can't say that I saw any significant difference in my tests. Sysinfo is not very good at using as a benchmark tool either, as it's not very consistent (maybe due to JIT?). I've had mixed results in subsequent runs with Sysinfo 4, from worse to better than the cortex-a7 build.
In the end, I thought it was best to leave it at that for now, until we know more.

In the meantime, I'm also working on updating the sources to merge some bug fixes from Lubomyr's Android version. I was thinking that after that step I could try to see how much we can update from the main WinUAE sources as well.

Once I'm done and I've tested the results, I'll send you a new pull request. We would all benefit from a better version of uae4arm :)

**Comment by midwan** [comment]
OK, I run some more tests with today's build, and there are some improvements with the latest flags I used on the Pi 3 vs Pi 2 build, at least regarding CPU speed.

Here are some screenshots from running SysSpeed, on the same RPI3 and same Workbench 3.9 installation. I used JIT, Fastest Possible, emulating a 68040.

Using the RPI3 optimized build:
img_20160828_210619

Using the RPI2 build:
img_20160828_210521

So i think it's worth it to use the optimal flags for each platform.

**Comment by joolswills** [comment]
just my 2c, but not sure why you have all this stuck in one PR - wouldn't it make more sense to split it out ?

**Comment by midwan** [comment]
This was originally just one PR, about the Makefile changes. Since then, I have continued to work on the code however, and because the PR has not changed status (not accepted, not closed) it keeps including the new stuff. I'm not sure if there's a way to stop that short of closing it?

**Pull request closed without merging**
